@startuml
'https://plantuml.com/sequence-diagram

class Item {
+ String Name
+ contextMenuForTabPanes contextMenu
+ addTabPaneToAnchorPane()
}

anchorPane o-- tabPane : contains >
tabPane *-- tab : contains >
tab o-- accordion : contains >
accordion *-- titledPane : contains >

tabPane o-- contextMenuForTabPanes : contains >
tab o-- contextMenuForTabs : contains >
titledPane o-- contextMenuForTitledPanes : contains >

@enduml